### ISSUE TITLE
Awesome work !

### ISSUE THREAD

**Issue by kaiyes** [chenr2/AWS-SAM-Tutorial#1]
Hi, 
Just found your talk on youtube ! Gotta say, you have a very clear way of teaching. It feels like you are quite gifted at teaching code to people. Ever thought about that pathway ? There are people who has become wildly famous for teaching code in udemy. Two example are [stephen grider](https://www.udemy.com/user/sgslo/) and [rob percival](https://www.udemy.com/user/robpercival/) 

Do think about it. You can always do it on the side. If you want video editing help, I am here :D 

Thanks ! (sorry for reaching you here ! ain't the right place I know !)

**Comment by chenr2** [comment]
@kaiyes Thank you so much for those kind words! I'll keep these things in mind.

**Comment by kaiyes** [comment]
By the way @chenr2  what's your preferred social media to interact with strangers :D Linkedin or twitter ? Would love to have a quick conversation with you about sam vs serverless for developing serverless apps. The recent sam local announcement in re-invent got me curious ! 

Here is my linkedIn 
https://www.linkedin.com/in/kaiyes-ansary-813168136/

**Comment by chenr2** [comment]
My twitter handle is [@robcornerstone](https://twitter.com/robcornerstone).
